package tests

import "lab8/model"

const baseUrl = "http://shop.qatl.ru"

var (
	commonCategoryID  = "5"
	commonTitle       = "Test title"
	commonContent     = "This product"
	commonPrice       = "100"
	commonOldPrice    = "200"
	commonStatus      = "1"
	commonKeywords    = "test, banana"
	commonDescription = "Test product description"
	commonHit         = "1"
)

var validProductMinCategoryId = model.Product{
	CategoryID:  "1",
	Title:       commonTitle,
	Content:     commonContent,
	Price:       commonPrice,
	OldPrice:    commonOldPrice,
	Status:      commonStatus,
	Keywords:    commonKeywords,
	Description: commonDescription,
	Hit:         commonHit,
}

var validCases = map[string]model.Product{
	"valid_product_min_category_id": validProductMinCategoryId,
	"valid_product_max_category_id": {
		CategoryID:  "14",
		Title:       commonTitle,
		Content:     commonContent,
		Price:       commonPrice,
		OldPrice:    commonOldPrice,
		Status:      commonStatus,
		Keywords:    commonKeywords,
		Description: commonDescription,
		Hit:         commonHit,
	},
	"valid_product_min_title": {
		CategoryID:  commonCategoryID,
		Title:       "",
		Content:     commonContent,
		Price:       commonPrice,
		OldPrice:    commonOldPrice,
		Status:      commonStatus,
		Keywords:    commonKeywords,
		Description: commonDescription,
		Hit:         commonHit,
	},
	"valid_product_max_title": {
		CategoryID:  commonCategoryID,
		Title:       string(make([]byte, 255)),
		Content:     commonContent,
		Price:       commonPrice,
		OldPrice:    commonOldPrice,
		Status:      commonStatus,
		Keywords:    commonKeywords,
		Description: commonDescription,
		Hit:         commonHit,
	},
	"valid_product_min_content": {
		CategoryID:  commonCategoryID,
		Title:       commonTitle,
		Content:     "",
		Price:       commonPrice,
		OldPrice:    commonOldPrice,
		Status:      commonStatus,
		Keywords:    commonKeywords,
		Description: commonDescription,
		Hit:         commonHit,
	},
	"valid_product_max_content": {
		CategoryID:  commonCategoryID,
		Title:       commonTitle,
		Content:     string(make([]byte, 65535)),
		Price:       commonPrice,
		OldPrice:    commonOldPrice,
		Status:      commonStatus,
		Keywords:    commonKeywords,
		Description: commonDescription,
		Hit:         commonHit,
	},
	"valid_product_min_price": {
		CategoryID:  commonCategoryID,
		Title:       commonTitle,
		Content:     commonContent,
		Price:       "-99999999999999999999999999999999999999",
		OldPrice:    commonOldPrice,
		Status:      commonStatus,
		Keywords:    commonKeywords,
		Description: commonDescription,
		Hit:         commonHit,
	},
	"valid_product_max_price": {
		CategoryID:  commonCategoryID,
		Title:       commonTitle,
		Content:     commonContent,
		Price:       "99999999999999999999999999999999999999",
		OldPrice:    commonOldPrice,
		Status:      commonStatus,
		Keywords:    commonKeywords,
		Description: commonDescription,
		Hit:         commonHit,
	},
	"valid_product_min_old_price": {
		CategoryID:  commonCategoryID,
		Title:       commonTitle,
		Content:     commonContent,
		Price:       commonPrice,
		OldPrice:    "1",
		Status:      commonStatus,
		Keywords:    commonKeywords,
		Description: commonDescription,
		Hit:         commonHit,
	},
	"valid_product_max_old_price": {
		CategoryID:  commonCategoryID,
		Title:       commonTitle,
		Content:     commonContent,
		Price:       "1",
		OldPrice:    "99999999999999999999999999999999999999",
		Status:      commonStatus,
		Keywords:    commonKeywords,
		Description: commonDescription,
		Hit:         commonHit,
	},
	"valid_product_min_status": {
		CategoryID:  commonCategoryID,
		Title:       commonTitle,
		Content:     commonContent,
		Price:       commonPrice,
		OldPrice:    commonOldPrice,
		Status:      "0",
		Keywords:    commonKeywords,
		Description: commonDescription,
		Hit:         commonHit,
	},
	"valid_product_max_status": {
		CategoryID:  commonCategoryID,
		Title:       commonTitle,
		Content:     commonContent,
		Price:       commonPrice,
		OldPrice:    commonOldPrice,
		Status:      "1",
		Keywords:    commonKeywords,
		Description: commonDescription,
		Hit:         commonHit,
	},
	"valid_product_min_keywords": {
		CategoryID:  commonCategoryID,
		Title:       commonTitle,
		Content:     commonContent,
		Price:       commonPrice,
		OldPrice:    commonOldPrice,
		Status:      commonStatus,
		Keywords:    "",
		Description: commonDescription,
		Hit:         commonHit,
	},
	"valid_product_max_keywords": {
		CategoryID:  commonCategoryID,
		Title:       commonTitle,
		Content:     commonContent,
		Price:       commonPrice,
		OldPrice:    commonOldPrice,
		Status:      commonStatus,
		Keywords:    string(make([]byte, 255)),
		Description: commonDescription,
		Hit:         commonHit,
	},
	"valid_product_min_description": {
		CategoryID:  commonCategoryID,
		Title:       commonTitle,
		Content:     commonContent,
		Price:       commonPrice,
		OldPrice:    commonOldPrice,
		Status:      commonStatus,
		Keywords:    commonKeywords,
		Description: "",
		Hit:         commonHit,
	},
	"valid_product_max_description": {
		CategoryID:  commonCategoryID,
		Title:       commonTitle,
		Content:     commonContent,
		Price:       commonPrice,
		OldPrice:    commonOldPrice,
		Status:      commonStatus,
		Keywords:    commonKeywords,
		Description: string(make([]byte, 255)),
		Hit:         commonHit,
	},
	"valid_product_min_hit": {
		CategoryID:  commonCategoryID,
		Title:       commonTitle,
		Content:     commonContent,
		Price:       commonPrice,
		OldPrice:    commonOldPrice,
		Status:      commonStatus,
		Keywords:    commonKeywords,
		Description: commonDescription,
		Hit:         "0",
	},
	"valid_product_max_hit": {
		CategoryID:  commonCategoryID,
		Title:       commonTitle,
		Content:     commonContent,
		Price:       commonPrice,
		OldPrice:    commonOldPrice,
		Status:      commonStatus,
		Keywords:    commonKeywords,
		Description: commonDescription,
		Hit:         "1",
	},
}

var invalidCases = map[string]model.Product{
	"invalid_type_category_id": {
		CategoryID:  "abc",
		Title:       commonTitle,
		Content:     commonContent,
		Price:       commonPrice,
		OldPrice:    commonOldPrice,
		Status:      commonStatus,
		Keywords:    commonKeywords,
		Description: commonDescription,
		Hit:         commonHit,
	},
	"invalid_category_id_below_range": {
		CategoryID:  "-1",
		Title:       commonTitle,
		Content:     commonContent,
		Price:       commonPrice,
		OldPrice:    commonOldPrice,
		Status:      commonStatus,
		Keywords:    commonKeywords,
		Description: commonDescription,
		Hit:         commonHit,
	},
	"invalid_category_id_above_range": {
		CategoryID:  "99",
		Title:       commonTitle,
		Content:     commonContent,
		Price:       commonPrice,
		OldPrice:    commonOldPrice,
		Status:      commonStatus,
		Keywords:    commonKeywords,
		Description: commonDescription,
		Hit:         commonHit,
	},
	"invalid_title_above_range": {
		CategoryID:  commonCategoryID,
		Title:       string(make([]byte, 256)),
		Content:     commonContent,
		Price:       commonPrice,
		OldPrice:    commonOldPrice,
		Status:      commonStatus,
		Keywords:    commonKeywords,
		Description: commonDescription,
		Hit:         commonHit,
	},
	"invalid_content_above_range": {
		CategoryID:  commonCategoryID,
		Title:       commonTitle,
		Content:     string(make([]byte, 65536)),
		Price:       commonPrice,
		OldPrice:    commonOldPrice,
		Status:      commonStatus,
		Keywords:    commonKeywords,
		Description: commonDescription,
		Hit:         commonHit,
	},
	"invalid_price_type": {
		CategoryID:  commonCategoryID,
		Title:       commonTitle,
		Content:     commonContent,
		Price:       "abc",
		OldPrice:    commonOldPrice,
		Status:      commonStatus,
		Keywords:    commonKeywords,
		Description: commonDescription,
		Hit:         commonHit,
	},
	"invalid_price_below_range": {
		CategoryID:  commonCategoryID,
		Title:       commonTitle,
		Content:     commonContent,
		Price:       "-999999999999999999999999999999999999999",
		OldPrice:    commonOldPrice,
		Status:      commonStatus,
		Keywords:    commonKeywords,
		Description: commonDescription,
		Hit:         commonHit,
	},
	"invalid_price_above_range": {
		CategoryID:  commonCategoryID,
		Title:       commonTitle,
		Content:     commonContent,
		Price:       "999999999999999999999999999999999999999",
		OldPrice:    commonOldPrice,
		Status:      commonStatus,
		Keywords:    commonKeywords,
		Description: commonDescription,
		Hit:         commonHit,
	},
	"invalid_old_price_type": {
		CategoryID:  commonCategoryID,
		Title:       commonTitle,
		Content:     commonContent,
		Price:       commonPrice,
		OldPrice:    "abc",
		Status:      commonStatus,
		Keywords:    commonKeywords,
		Description: commonDescription,
		Hit:         commonHit,
	},
	"invalid_old_price_below_range": {
		CategoryID:  commonCategoryID,
		Title:       commonTitle,
		Content:     commonContent,
		Price:       commonPrice,
		OldPrice:    "-999999999999999999999999999999999999999",
		Status:      commonStatus,
		Keywords:    commonKeywords,
		Description: commonDescription,
		Hit:         commonHit,
	},
	"invalid_old_price_above_range": {
		CategoryID:  commonCategoryID,
		Title:       commonTitle,
		Content:     commonContent,
		Price:       commonPrice,
		OldPrice:    "999999999999999999999999999999999999999",
		Status:      commonStatus,
		Keywords:    commonKeywords,
		Description: commonDescription,
		Hit:         commonHit,
	},
	"invalid_keywords_above_range": {
		CategoryID:  commonCategoryID,
		Title:       commonTitle,
		Content:     commonContent,
		Price:       commonPrice,
		OldPrice:    commonOldPrice,
		Status:      commonStatus,
		Keywords:    string(make([]byte, 256)),
		Description: commonDescription,
		Hit:         commonHit,
	},
	"invalid_description_above_range": {
		CategoryID:  commonCategoryID,
		Title:       commonTitle,
		Content:     commonContent,
		Price:       commonPrice,
		OldPrice:    commonOldPrice,
		Status:      commonStatus,
		Keywords:    commonKeywords,
		Description: string(make([]byte, 256)),
		Hit:         commonHit,
	},
	"invalid_category_id_empty": {
		Title:       commonTitle,
		Content:     commonContent,
		Price:       commonPrice,
		OldPrice:    commonOldPrice,
		Status:      commonStatus,
		Keywords:    commonKeywords,
		Description: commonDescription,
		Hit:         commonHit,
	},
	"invalid_price_empty": {
		CategoryID:  commonCategoryID,
		Title:       commonTitle,
		Content:     commonContent,
		OldPrice:    commonOldPrice,
		Status:      commonStatus,
		Keywords:    commonKeywords,
		Description: commonDescription,
		Hit:         commonHit,
	},
	"invalid_old_price_empty": {
		CategoryID:  commonCategoryID,
		Title:       commonTitle,
		Content:     commonContent,
		Price:       commonPrice,
		Status:      commonStatus,
		Keywords:    commonKeywords,
		Description: commonDescription,
		Hit:         commonHit,
	},
	"invalid_empty_product": {},
}
